-- 1. member 테이블
-- id : 문자열 (20바이트) primary key
-- password : 문자열(10바이트) not null
-- member_name : 문자열(30바이트)
-- email : 문자열(30바이트) '@' 포함 
-- phone : 문자열(20바이트)

CREATE TABLE MEMBER(
	ID VARCHAR2(20) CONSTRAINT MEMBER_ID_PK PRIMARY KEY,
	PW VARCHAR2(10) CONSTRAINT MEMBER_PW_NN NOT NULL,
	MEMBER_NAME VARCHAR2(30),
	EMAIL VARCHAR2(30) CONSTRAINT MEMBER_EMAIL_CK CHECK (EMAIL LIKE '%@%'),
	PHONE VARCHAR2(20)
)

SELECT * FROM MEMBER;

-- 2. board 테이블 (이미 정의 ==> 수정) 
-- writer member  테이블 id 컬럼 존재값 참조
-- 1>
-- drop table board;
-- create table board....

CREATE TABLE BOARD(
	SEQ		NUMBER(5) CONSTRAINT BOARD_SEQ_PK PRIMARY KEY,
	TITLE	VARCHAR2(50)	CONSTRAINT BOARD_TITLE_NN NOT NULL,
	CONTENTS	VARCHAR2(4000),
	WRITER	VARCHAR2(20) CONSTRAINT BOARD_WRITER_FK REFERENCES MEMBER(ID),
	TIME	DATE,
	PW	VARCHAR2(30),
	VIEWCOUNT	NUMBER(5)	CONSTRAINT BOARD_VIEWCOUNT_CK CHECK (VIEWCOUNT >= 0)
)

SELECT * FROM BOARD;

-- 2> alter table board modify
-- (writer member  테이블 id 컬럼 타입 
-- 제약조건 member  테이블 id 컬럼 존재값 참조)

ALTER TABLE BOARD MODIFY (WRITER VARCHAR2(20) CONSTRAINT BOARD_WRITER_FK REFERENCES MEMBER(ID));

CREATE SEQUENCE BOARD_SEQUENCE
START WITH 1
INCREMENT BY 1




DROP SEQUENCE BOARD_SEQUENCE

DROP TABLE BOARD;
DROP TABLE MEMBER;
